ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_rsa_droplet

app_name: my-app
app_dir: /opt/my-app

docker_app_image: "ghcr.io/tahatsahin/node-server:latest"
docker_app_port: 3000

nginx_server_name: "_"

